name: build

on:
    push:
    pull_request:

jobs:

  build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 16.13.1
        - run: |
            cd capstone_project/hello-world/
            npm i
        - run: |
            cd capstone_project/hello-world/
            npm run build --if-present
        - run: |
            cd capstone_project/hello-world/
            npm test

  buildDocker:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: build container
          working-directory: capstone_project/hello-world/
          run: docker build -t hello-world .
